-- Script was generated by Devart dbForge Studio for MySQL, Version 5.0.67.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 07/09/2012 21:17:18
-- Server version: 5.5.20-log
-- Client version: 4.1

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Definition for database dbhestia_desarrollo
--
DROP DATABASE IF EXISTS dbhestia_desarrollo;
CREATE DATABASE dbhestia_desarrollo
	CHARACTER SET latin1
	COLLATE latin1_swedish_ci;

-- 
-- Set default database
--
USE dbhestia_desarrollo;

--
-- Definition for table kz_hestia_centro_atencion
--
CREATE TABLE kz_hestia_centro_atencion (
  IdCentroAtencion SMALLINT(6) NOT NULL AUTO_INCREMENT,
  NombreCentroAtencion VARCHAR(50) NOT NULL,
  NumeroPuntosAtencion SMALLINT(6) NOT NULL DEFAULT 0,
  PRIMARY KEY (IdCentroAtencion)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table kz_hestia_cronograma_academica
--
CREATE TABLE kz_hestia_cronograma_academica (
  IdCronogramaAcademico SMALLINT(6) NOT NULL AUTO_INCREMENT,
  AnioAcademico INT(11) NOT NULL,
  Semestre TINYINT(4) NOT NULL,
  FechaInicio DATE NOT NULL,
  FechaCulminacion DATE NOT NULL,
  PRIMARY KEY (IdCronogramaAcademico),
  UNIQUE INDEX IdCronogramaAcademico (IdCronogramaAcademico)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table kz_hestia_facultad
--
CREATE TABLE kz_hestia_facultad (
  IdFacultad INT(11) NOT NULL AUTO_INCREMENT,
  NombreFacultad VARCHAR(50) NOT NULL,
  PRIMARY KEY (IdFacultad),
  UNIQUE INDEX NombreFacultad (NombreFacultad)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table kz_hestia_justificacion
--
CREATE TABLE kz_hestia_justificacion (
  IdJustificacion BIGINT(20) NOT NULL AUTO_INCREMENT,
  IdTiempo INT(11) NOT NULL,
  Fecha DATE NOT NULL,
  Motivo VARCHAR(300) NOT NULL,
  PRIMARY KEY (IdJustificacion)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table kz_hestia_permiso
--
CREATE TABLE kz_hestia_permiso (
  IdPermiso INT(11) NOT NULL AUTO_INCREMENT,
  ClavePermiso VARCHAR(30) NOT NULL,
  NombrePermiso VARCHAR(50) NOT NULL,
  FechaCreacion DATETIME NOT NULL,
  FechaActualizacion DATETIME DEFAULT NULL,
  PRIMARY KEY (IdPermiso)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table kz_hestia_rol
--
CREATE TABLE kz_hestia_rol (
  IdRol INT(11) NOT NULL AUTO_INCREMENT,
  NombreRol VARCHAR(50) NOT NULL,
  FechaCreacion DATETIME NOT NULL,
  FechaActualizacion DATETIME DEFAULT NULL,
  PRIMARY KEY (IdRol),
  UNIQUE INDEX NombreRol (NombreRol)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table kz_hestia_tiempo
--
CREATE TABLE kz_hestia_tiempo (
  IdTiempo BIGINT(20) NOT NULL AUTO_INCREMENT,
  NumeroDia SMALLINT(6) NOT NULL,
  NumeroMes TINYINT(4) DEFAULT NULL,
  NumeroAnio INT(11) NOT NULL,
  Fecha DATE NOT NULL,
  PRIMARY KEY (IdTiempo),
  UNIQUE INDEX Fecha (Fecha)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table kz_hestia_carrera_profesional
--
CREATE TABLE kz_hestia_carrera_profesional (
  IdCarreraProfesional INT(11) NOT NULL AUTO_INCREMENT,
  IdFacultad INT(11) NOT NULL,
  NombreCarreraProfesional VARCHAR(50) NOT NULL,
  PRIMARY KEY (IdCarreraProfesional),
  INDEX FK_kz_hestia_carrera_profesional_kz_hestia_facultad_IdFacultad (IdFacultad),
  UNIQUE INDEX NombreCarreraProfesional (NombreCarreraProfesional),
  CONSTRAINT FK_kz_hestia_carrera_profesional_kz_hestia_facultad_IdFacultad FOREIGN KEY (IdFacultad)
    REFERENCES kz_hestia_facultad(IdFacultad) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table kz_hestia_rol_permiso
--
CREATE TABLE kz_hestia_rol_permiso (
  IdRolPermiso INT(11) NOT NULL AUTO_INCREMENT,
  IdRol INT(11) NOT NULL,
  IdPermiso INT(11) NOT NULL,
  Valor TINYINT(1) NOT NULL DEFAULT 0,
  FechaCreacion DATETIME NOT NULL,
  PRIMARY KEY (IdRolPermiso),
  INDEX FK_kz_hestia_rol_permiso_kz_hestia_permiso_IdPermiso (IdPermiso),
  INDEX FK_kz_hestia_rol_permiso_kz_hestia_rol_IdRol (IdRol),
  CONSTRAINT FK_kz_hestia_rol_permiso_kz_hestia_permiso_IdPermiso FOREIGN KEY (IdPermiso)
    REFERENCES kz_hestia_permiso(IdPermiso) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_kz_hestia_rol_permiso_kz_hestia_rol_IdRol FOREIGN KEY (IdRol)
    REFERENCES kz_hestia_rol(IdRol) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table kz_hestia_persona
--
CREATE TABLE kz_hestia_persona (
  IdPersona BIGINT(20) NOT NULL AUTO_INCREMENT,
  IdTipoPersona INT(11) NOT NULL,
  DNI VARCHAR(15) NOT NULL,
  CodigoUniversitario VARCHAR(15) DEFAULT NULL,
  IdCarreraProfesional INT(11) DEFAULT NULL,
  NumCiclo VARCHAR(255) DEFAULT NULL,
  ApellidoPaterno VARCHAR(50) NOT NULL,
  ApellidoMaterno VARCHAR(50) NOT NULL,
  NombresCompleto VARCHAR(100) NOT NULL,
  Sexo CHAR(255) NOT NULL,
  FechaNacimiento DATETIME DEFAULT NULL,
  CiudadProcedencia VARCHAR(50) DEFAULT NULL,
  TelefonoFijo VARCHAR(15) DEFAULT NULL,
  Celular1 VARCHAR(15) DEFAULT NULL,
  Celular2 VARCHAR(15) DEFAULT NULL,
  CorreoElectronicoPersonal VARCHAR(30) DEFAULT NULL,
  CorreoElectronicoInstitucional VARCHAR(30) DEFAULT NULL,
  FechaCreacion DATETIME NOT NULL,
  FechaActualizacion DATETIME DEFAULT NULL,
  PRIMARY KEY (IdPersona),
  UNIQUE INDEX DNI (DNI),
  INDEX FK_kz_hestia_carrera_profesional_IdCarreraProfesional (IdCarreraProfesional),
  CONSTRAINT FK_kz_hestia_carrera_profesional_IdCarreraProfesional FOREIGN KEY (IdCarreraProfesional)
    REFERENCES kz_hestia_carrera_profesional(IdCarreraProfesional) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table kz_hestia_atencion
--
CREATE TABLE kz_hestia_atencion (
  IdAtencion BIGINT(20) NOT NULL AUTO_INCREMENT,
  IdCentroAtencion INT(11) NOT NULL,
  IdPersona BIGINT(20) NOT NULL,
  IdBeneficiado INT(11) DEFAULT NULL,
  IdTiempo BIGINT(20) NOT NULL,
  HoraAtencion DATETIME NOT NULL,
  PRIMARY KEY (IdAtencion),
  INDEX FK_kz_hestia_atencion_kz_hestia_punto_atencion_IdPuntoAtencion (IdCentroAtencion),
  INDEX FK_kz_hestia_atencion_kz_hestia_tiempo_IdTiempo (IdTiempo),
  UNIQUE INDEX UK_kz_hestia_atencion (IdPersona, IdTiempo),
  CONSTRAINT FK_kz_hestia_atencion_kz_hestia_persona_IdPersona FOREIGN KEY (IdPersona)
    REFERENCES kz_hestia_persona(IdPersona) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_kz_hestia_atencion_kz_hestia_tiempo_IdTiempo FOREIGN KEY (IdTiempo)
    REFERENCES kz_hestia_tiempo(IdTiempo) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 59
AVG_ROW_LENGTH = 16384
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table kz_hestia_beneficiado
--
CREATE TABLE kz_hestia_beneficiado (
  IdBeneficiado INT(11) NOT NULL AUTO_INCREMENT,
  IdPersona BIGINT(20) NOT NULL,
  IdCronogramaAcademico SMALLINT(6) NOT NULL,
  IdCarreraProfesional INT(11) NOT NULL,
  IdFacultad INT(11) NOT NULL,
  NumCiclo TINYINT(4) NOT NULL,
  DNI VARCHAR(15) NOT NULL,
  Sexo CHAR(255) NOT NULL,
  CodigoUniversitario VARCHAR(15) NOT NULL,
  IdCondicionFinal INT(11) NOT NULL,
  CondicionFinal VARCHAR(30) NOT NULL DEFAULT 'Habilitado',
  FechaCreacion DATETIME NOT NULL,
  FechaActualizacion DATETIME NOT NULL,
  NombresCompletos VARCHAR(150) NOT NULL,
  PRIMARY KEY (IdBeneficiado),
  UNIQUE INDEX CodigoUniversitario (CodigoUniversitario),
  UNIQUE INDEX DNI (DNI),
  UNIQUE INDEX IdPersona (IdPersona),
  CONSTRAINT FK_kz_hestia_beneficiado_kz_hestia_persona_IdPersona FOREIGN KEY (IdPersona)
    REFERENCES kz_hestia_persona(IdPersona) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table kz_hestia_historial_persona
--
CREATE TABLE kz_hestia_historial_persona (
  IdHistorialPersona INT(11) NOT NULL AUTO_INCREMENT,
  IdPersona BIGINT(20) NOT NULL,
  IdCronogramaAcademico SMALLINT(6) NOT NULL,
  DiasProgramados SMALLINT(6) NOT NULL,
  DiasAsistidos SMALLINT(6) NOT NULL,
  DiasJustificados SMALLINT(6) NOT NULL,
  DiasNoAsistidos SMALLINT(6) NOT NULL,
  DiasNoAsistidosSeguidos SMALLINT(6) NOT NULL,
  DiasNoAsistidosAlternados SMALLINT(6) NOT NULL,
  PRIMARY KEY (IdHistorialPersona),
  INDEX FK_kz_hestia_historial_persona_kz_hestia_IdCronogramaAcademico (IdCronogramaAcademico),
  INDEX FK_kz_hestia_historial_persona_kz_hestia_persona_IdPersona (IdPersona),
  CONSTRAINT FK_kz_hestia_historial_persona_kz_hestia_IdCronogramaAcademico FOREIGN KEY (IdCronogramaAcademico)
    REFERENCES kz_hestia_cronograma_academica(IdCronogramaAcademico) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_kz_hestia_historial_persona_kz_hestia_persona_IdPersona FOREIGN KEY (IdPersona)
    REFERENCES kz_hestia_persona(IdPersona) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table kz_hestia_usuario
--
CREATE TABLE kz_hestia_usuario (
  IdUsuario INT(11) NOT NULL AUTO_INCREMENT,
  NombreUsuario VARCHAR(30) NOT NULL,
  `Password` VARCHAR(30) NOT NULL,
  IdPersona BIGINT(20) NOT NULL,
  IdCentroAtencion INT(11) NOT NULL,
  FechaCreacion DATETIME NOT NULL,
  PRIMARY KEY (IdUsuario),
  UNIQUE INDEX IdPersona (IdPersona),
  UNIQUE INDEX NombreUsuario (NombreUsuario),
  CONSTRAINT FK_kz_hestia_usuario_kz_hestia_persona_IdPersona FOREIGN KEY (IdPersona)
    REFERENCES kz_hestia_persona(IdPersona) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table kz_hestia_asistencia
--
CREATE TABLE kz_hestia_asistencia (
  IdAsistencia BIGINT(20) NOT NULL AUTO_INCREMENT,
  TipoAsistencia CHAR(1) NOT NULL,
  IdAtencion BIGINT(20) NOT NULL,
  IdCentroAtencion SMALLINT(6) NOT NULL,
  IdTiempo INT(11) NOT NULL,
  IdBeneficiado INT(11) NOT NULL,
  IdPersona INT(11) NOT NULL,
  HoraAtencion DATETIME NOT NULL,
  PRIMARY KEY (IdAsistencia),
  INDEX FK_kz_hestia_asistencia_kz_hestia_beneficiado_IdBeneficiado (IdBeneficiado),
  UNIQUE INDEX IdAtencion (IdAtencion),
  CONSTRAINT FK_kz_hestia_asistencia_kz_hestia_atencion_IdAtencion FOREIGN KEY (IdAtencion)
    REFERENCES kz_hestia_atencion(IdAtencion) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_kz_hestia_asistencia_kz_hestia_beneficiado_IdBeneficiado FOREIGN KEY (IdBeneficiado)
    REFERENCES kz_hestia_beneficiado(IdBeneficiado) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table kz_hestia_usuario_permiso
--
CREATE TABLE kz_hestia_usuario_permiso (
  IdUsuarioPermiso INT(11) NOT NULL AUTO_INCREMENT,
  IdUsuario INT(11) NOT NULL,
  IdPermiso INT(11) NOT NULL,
  Valor TINYINT(1) NOT NULL DEFAULT 0,
  FechaCreacion DATETIME NOT NULL,
  PRIMARY KEY (IdUsuarioPermiso),
  INDEX FK_kz_hestia_usuario_permiso_kz_hestia_permiso_IdPermiso (IdPermiso),
  INDEX FK_kz_hestia_usuario_permiso_kz_hestia_usuario_IdUsuario (IdUsuario),
  CONSTRAINT FK_kz_hestia_usuario_permiso_kz_hestia_permiso_IdPermiso FOREIGN KEY (IdPermiso)
    REFERENCES kz_hestia_permiso(IdPermiso) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_kz_hestia_usuario_permiso_kz_hestia_usuario_IdUsuario FOREIGN KEY (IdUsuario)
    REFERENCES kz_hestia_usuario(IdUsuario) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table kz_hestia_usuario_rol
--
CREATE TABLE kz_hestia_usuario_rol (
  IdUsuarioRol INT(11) NOT NULL AUTO_INCREMENT,
  IdUsuario INT(11) NOT NULL,
  IdRol INT(11) NOT NULL,
  Valor TINYINT(1) NOT NULL DEFAULT 0,
  FechaCreacion DATETIME NOT NULL,
  PRIMARY KEY (IdUsuarioRol),
  INDEX FK_kz_hestia_usuario_rol_kz_hestia_rol_IdRol (IdRol),
  INDEX FK_kz_hestia_usuario_rol_kz_hestia_usuario_IdUsuario (IdUsuario),
  CONSTRAINT FK_kz_hestia_usuario_rol_kz_hestia_rol_IdRol FOREIGN KEY (IdRol)
    REFERENCES kz_hestia_rol(IdRol) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_kz_hestia_usuario_rol_kz_hestia_usuario_IdUsuario FOREIGN KEY (IdUsuario)
    REFERENCES kz_hestia_usuario(IdUsuario) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

-- 
-- Dumping data for table kz_hestia_centro_atencion
--
INSERT INTO kz_hestia_centro_atencion VALUES 
  (1, 'DON VITTOR', 3);

-- 
-- Dumping data for table kz_hestia_cronograma_academica
--
INSERT INTO kz_hestia_cronograma_academica VALUES 
  (1, 2012, 2, '2012-09-07', '2012-09-14');

-- 
-- Dumping data for table kz_hestia_facultad
--
INSERT INTO kz_hestia_facultad VALUES 
  (1, 'Ingeniería Industrial, Sistemas e Informática');

-- 
-- Dumping data for table kz_hestia_justificacion
--
-- Table dbhestia_desarrollo.kz_hestia_justificacion does not contain any data (it is empty)

-- 
-- Dumping data for table kz_hestia_permiso
--
INSERT INTO kz_hestia_permiso VALUES 
  (1, 'marcadoAsistencia', 'MarcadoAsistencia', '2012-09-05 22:12:25', NULL);

-- 
-- Dumping data for table kz_hestia_rol
--
-- Table dbhestia_desarrollo.kz_hestia_rol does not contain any data (it is empty)

-- 
-- Dumping data for table kz_hestia_tiempo
--
INSERT INTO kz_hestia_tiempo VALUES 
  (1, 7, 9, 2012, '2012-09-07');

-- 
-- Dumping data for table kz_hestia_carrera_profesional
--
INSERT INTO kz_hestia_carrera_profesional VALUES 
  (1, 1, 'Ingenieria Informatica');

-- 
-- Dumping data for table kz_hestia_rol_permiso
--
-- Table dbhestia_desarrollo.kz_hestia_rol_permiso does not contain any data (it is empty)

-- 
-- Dumping data for table kz_hestia_persona
--
INSERT INTO kz_hestia_persona VALUES 
  (1, 1, '72324881', '0333081003', 1, '10', 'MANRIQUE', 'LEZAMETA', 'ELIZABETH CRISTINA', 'F', '1991-07-04 00:00:00', 'Hualmay', '2395044', '966418283', NULL, 'emanriquel@hotmail.com', '0333081003@unjfsc.edu.pe', '0000-00-00 00:00:00', NULL);

-- 
-- Dumping data for table kz_hestia_atencion
--
INSERT INTO kz_hestia_atencion VALUES 
  (51, 1, 1, 1, 1, '2012-09-07 20:29:57');

-- 
-- Dumping data for table kz_hestia_beneficiado
--
INSERT INTO kz_hestia_beneficiado VALUES 
  (1, 1, 1, 1, 1, 1, '72324881', 'F', '0333081003', 1, 'HABILITADO', '2012-09-07 21:12:20', '0000-00-00 00:00:00', 'MANRIQUE ELIZABETH');

-- 
-- Dumping data for table kz_hestia_historial_persona
--
-- Table dbhestia_desarrollo.kz_hestia_historial_persona does not contain any data (it is empty)

-- 
-- Dumping data for table kz_hestia_usuario
--
INSERT INTO kz_hestia_usuario VALUES 
  (1, '72324881', '123456', 1, 1, '2012-09-05 02:00:13');

-- 
-- Dumping data for table kz_hestia_asistencia
--
-- Table dbhestia_desarrollo.kz_hestia_asistencia does not contain any data (it is empty)

-- 
-- Dumping data for table kz_hestia_usuario_permiso
--
INSERT INTO kz_hestia_usuario_permiso VALUES 
  (1, 1, 1, 1, '2012-09-05 00:00:00');

-- 
-- Dumping data for table kz_hestia_usuario_rol
--
-- Table dbhestia_desarrollo.kz_hestia_usuario_rol does not contain any data (it is empty)

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;